// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.aws.jvtsa.rekognition_liveness

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Temporary AWS credentials handed to the native liveness SDK, which signs the
 * WebSocket to Amazon Rekognition directly.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LivenessCredentialsMessage (
  val accessKeyId: String,
  val secretAccessKey: String,
  val sessionToken: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LivenessCredentialsMessage {
      val accessKeyId = pigeonVar_list[0] as String
      val secretAccessKey = pigeonVar_list[1] as String
      val sessionToken = pigeonVar_list[2] as String
      return LivenessCredentialsMessage(accessKeyId, secretAccessKey, sessionToken)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accessKeyId,
      secretAccessKey,
      sessionToken,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LivenessCredentialsMessage
    return MessagesPigeonUtils.deepEquals(this.accessKeyId, other.accessKeyId) && MessagesPigeonUtils.deepEquals(this.secretAccessKey, other.secretAccessKey) && MessagesPigeonUtils.deepEquals(this.sessionToken, other.sessionToken)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.accessKeyId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.secretAccessKey)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sessionToken)
    return result
  }
  override fun toString(): String {
    return "LivenessCredentialsMessage(accessKeyId=$accessKeyId, secretAccessKey=$secretAccessKey, sessionToken=$sessionToken)"
  }
}

/**
 * Result of a completed liveness check, surfaced by the native SDK.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LivenessResultMessage (
  val sessionId: String,
  val isLive: Boolean,
  val confidence: Double,
  val referenceImage: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LivenessResultMessage {
      val sessionId = pigeonVar_list[0] as String
      val isLive = pigeonVar_list[1] as Boolean
      val confidence = pigeonVar_list[2] as Double
      val referenceImage = pigeonVar_list[3] as ByteArray?
      return LivenessResultMessage(sessionId, isLive, confidence, referenceImage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sessionId,
      isLive,
      confidence,
      referenceImage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LivenessResultMessage
    return MessagesPigeonUtils.deepEquals(this.sessionId, other.sessionId) && MessagesPigeonUtils.deepEquals(this.isLive, other.isLive) && MessagesPigeonUtils.deepEquals(this.confidence, other.confidence) && MessagesPigeonUtils.deepEquals(this.referenceImage, other.referenceImage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sessionId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.isLive)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.confidence)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.referenceImage)
    return result
  }
  override fun toString(): String {
    return "LivenessResultMessage(sessionId=$sessionId, isLive=$isLive, confidence=$confidence, referenceImage=${referenceImage?.contentToString()})"
  }
}

/**
 * A native-side failure (SDK error, cancellation, or missing dependency).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class LivenessErrorMessage (
  val code: String,
  val message: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LivenessErrorMessage {
      val code = pigeonVar_list[0] as String
      val message = pigeonVar_list[1] as String
      return LivenessErrorMessage(code, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LivenessErrorMessage
    return MessagesPigeonUtils.deepEquals(this.code, other.code) && MessagesPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.code)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.message)
    return result
  }
  override fun toString(): String {
    return "LivenessErrorMessage(code=$code, message=$message)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LivenessCredentialsMessage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LivenessResultMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LivenessErrorMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is LivenessCredentialsMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is LivenessResultMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is LivenessErrorMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Dart -> native. Called once, after the platform view is created and Cognito
 * credentials have been fetched. Receiving credentials is the signal for the
 * native side to present the FaceLivenessDetectorView.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface LivenessHostApi {
  fun setCredentials(credentials: LivenessCredentialsMessage)

  companion object {
    /** The codec used by LivenessHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `LivenessHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LivenessHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.rekognition_liveness.LivenessHostApi.setCredentials$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val credentialsArg = args[0] as LivenessCredentialsMessage
            val wrapped: List<Any?> = try {
              api.setCredentials(credentialsArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Native -> Dart. Terminal callbacks; exactly one fires per session.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class LivenessFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by LivenessFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onComplete(resultArg: LivenessResultMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.rekognition_liveness.LivenessFlutterApi.onComplete$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(resultArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
  fun onError(errorArg: LivenessErrorMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.rekognition_liveness.LivenessFlutterApi.onError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
}
