// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Temporary AWS credentials handed to the native liveness SDK, which signs the
/// WebSocket to Amazon Rekognition directly.
///
/// Generated class from Pigeon that represents data sent in messages.
struct LivenessCredentialsMessage: Hashable, CustomStringConvertible {
  var accessKeyId: String
  var secretAccessKey: String
  var sessionToken: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LivenessCredentialsMessage? {
    let accessKeyId = pigeonVar_list[0] as! String
    let secretAccessKey = pigeonVar_list[1] as! String
    let sessionToken = pigeonVar_list[2] as! String

    return LivenessCredentialsMessage(
      accessKeyId: accessKeyId,
      secretAccessKey: secretAccessKey,
      sessionToken: sessionToken
    )
  }
  func toList() -> [Any?] {
    return [
      accessKeyId,
      secretAccessKey,
      sessionToken,
    ]
  }
  static func == (lhs: LivenessCredentialsMessage, rhs: LivenessCredentialsMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.accessKeyId, rhs.accessKeyId) && MessagesPigeonInternal.deepEquals(lhs.secretAccessKey, rhs.secretAccessKey) && MessagesPigeonInternal.deepEquals(lhs.sessionToken, rhs.sessionToken)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LivenessCredentialsMessage")
    MessagesPigeonInternal.deepHash(value: accessKeyId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: secretAccessKey, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sessionToken, hasher: &hasher)
  }

  public var description: String {
    return "LivenessCredentialsMessage(accessKeyId: \(String(describing: accessKeyId)), secretAccessKey: \(String(describing: secretAccessKey)), sessionToken: \(String(describing: sessionToken)))"
  }
}

/// Result of a completed liveness check, surfaced by the native SDK.
///
/// Generated class from Pigeon that represents data sent in messages.
struct LivenessResultMessage: Hashable, CustomStringConvertible {
  var sessionId: String
  var isLive: Bool
  var confidence: Double
  var referenceImage: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LivenessResultMessage? {
    let sessionId = pigeonVar_list[0] as! String
    let isLive = pigeonVar_list[1] as! Bool
    let confidence = pigeonVar_list[2] as! Double
    let referenceImage: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[3])

    return LivenessResultMessage(
      sessionId: sessionId,
      isLive: isLive,
      confidence: confidence,
      referenceImage: referenceImage
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      isLive,
      confidence,
      referenceImage,
    ]
  }
  static func == (lhs: LivenessResultMessage, rhs: LivenessResultMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && MessagesPigeonInternal.deepEquals(lhs.isLive, rhs.isLive) && MessagesPigeonInternal.deepEquals(lhs.confidence, rhs.confidence) && MessagesPigeonInternal.deepEquals(lhs.referenceImage, rhs.referenceImage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LivenessResultMessage")
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isLive, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: confidence, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: referenceImage, hasher: &hasher)
  }

  public var description: String {
    return "LivenessResultMessage(sessionId: \(String(describing: sessionId)), isLive: \(String(describing: isLive)), confidence: \(String(describing: confidence)), referenceImage: \(String(describing: referenceImage)))"
  }
}

/// A native-side failure (SDK error, cancellation, or missing dependency).
///
/// Generated class from Pigeon that represents data sent in messages.
struct LivenessErrorMessage: Hashable, CustomStringConvertible {
  var code: String
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LivenessErrorMessage? {
    let code = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String

    return LivenessErrorMessage(
      code: code,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
    ]
  }
  static func == (lhs: LivenessErrorMessage, rhs: LivenessErrorMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.code, rhs.code) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LivenessErrorMessage")
    MessagesPigeonInternal.deepHash(value: code, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "LivenessErrorMessage(code: \(String(describing: code)), message: \(String(describing: message)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return LivenessCredentialsMessage.fromList(self.readValue() as! [Any?])
    case 130:
      return LivenessResultMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return LivenessErrorMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? LivenessCredentialsMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? LivenessResultMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? LivenessErrorMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Dart -> native. Called once, after the platform view is created and Cognito
/// credentials have been fetched. Receiving credentials is the signal for the
/// native side to present the FaceLivenessDetectorView.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LivenessHostApi {
  func setCredentials(credentials: LivenessCredentialsMessage) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LivenessHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `LivenessHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LivenessHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let setCredentialsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.rekognition_liveness.LivenessHostApi.setCredentials\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCredentialsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let credentialsArg = args[0] as! LivenessCredentialsMessage
        do {
          try api.setCredentials(credentials: credentialsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setCredentialsChannel.setMessageHandler(nil)
    }
  }
}

/// Native -> Dart. Terminal callbacks; exactly one fires per session.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol LivenessFlutterApiProtocol {
  func onComplete(result resultArg: LivenessResultMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onError(error errorArg: LivenessErrorMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class LivenessFlutterApi: LivenessFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onComplete(result resultArg: LivenessResultMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.rekognition_liveness.LivenessFlutterApi.onComplete\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([resultArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onError(error errorArg: LivenessErrorMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.rekognition_liveness.LivenessFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
